# Generated by Django 5.2.17 on 2026-10-06 08:30

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0032_category_exclude_from_menu_category_long_description"),
        ("order", "0021_billingaddress_code_shippingaddress_code"),
        ("partner", "0007_partneraddress_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Населённый пункт"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "region",
                    models.CharField(
                        choices=[("77", "Москва"), ("50", "Московская область")],
                        max_length=2,
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Населённый пункт",
                "verbose_name_plural": "Населённые пункты",
                "ordering": ["region", "name"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="О магазине"),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес магазина"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        max_length=64,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=25, verbose_name="Телефон"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("review", "На проверке"),
                            ("active", "Активен"),
                            ("suspended", "Приостановлен"),
                        ],
                        default="review",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "delivery_enabled",
                    models.BooleanField(default=True, verbose_name="Доставка"),
                ),
                (
                    "pickup_enabled",
                    models.BooleanField(default=True, verbose_name="Самовывоз"),
                ),
                (
                    "radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Радиус доставки, км",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Доставка, ₽",
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Минимальная сумма товаров, ₽",
                    ),
                ),
                (
                    "prep_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[django.core.validators.MaxValueValidator(10080)],
                        verbose_name="Подготовка до получения, минут",
                    ),
                ),
                (
                    "pickup_instructions",
                    models.TextField(blank=True, verbose_name="Как забрать заказ"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Юридическое название"
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Расчётный счёт"
                    ),
                ),
                (
                    "bank_bik",
                    models.CharField(blank=True, max_length=9, verbose_name="БИК"),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Комиссия, %",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_settlements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="delivering_shops",
                        to="market.settlement",
                        verbose_name="Города доставки",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_shop",
                        to="partner.partner",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="market.settlement",
                        verbose_name="Населённый пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flower_kind",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Вид цветов"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bouquet", "Букеты"),
                            ("composition", "Композиции"),
                            ("stems", "Цветы поштучно"),
                        ],
                        default="bouquet",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="listings/%Y/%m/", verbose_name="Фото"
                    ),
                ),
                (
                    "seed_image",
                    models.CharField(blank=True, editable=False, max_length=128),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_listing",
                        to="catalogue.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="market.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение магазина",
                "verbose_name_plural": "Предложения магазинов",
            },
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.shop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="market.shop",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "shop"), name="market_unique_membership"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DateException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="Дата")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("work", "Работа магазина"),
                            ("delivery", "Доставка"),
                            ("pickup", "Самовывоз"),
                        ],
                        max_length=8,
                        verbose_name="Расписание",
                    ),
                ),
                ("closed", models.BooleanField(default=True, verbose_name="Выходной")),
                (
                    "start_minute",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(1439)],
                    ),
                ),
                (
                    "end_minute",
                    models.PositiveSmallIntegerField(
                        default=1440,
                        validators=[django.core.validators.MaxValueValidator(1440)],
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_exceptions",
                        to="market.shop",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "day", "method"), name="market_exception_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("delivery", "Доставка"), ("pickup", "Самовывоз")],
                        max_length=8,
                    ),
                ),
                ("slot_start", models.DateTimeField()),
                ("slot_end", models.DateTimeField()),
                ("address", models.CharField(max_length=300)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=25)),
                ("instructions", models.TextField(blank=True)),
                ("goods_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_total",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_total",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("partner_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Принят"),
                            ("preparing", "Собирается"),
                            ("ready", "Готов к выдаче"),
                            ("courier", "Передан курьеру"),
                            ("completed", "Получен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="accepted",
                        max_length=12,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("refunded", "Возвращён"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_orders",
                        to="order.order",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_orders",
                        to="market.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "shop"), name="market_order_shop"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklyHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(6)],
                        verbose_name="День недели",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("work", "Работа магазина"),
                            ("delivery", "Доставка"),
                            ("pickup", "Самовывоз"),
                        ],
                        max_length=8,
                        verbose_name="Расписание",
                    ),
                ),
                (
                    "start_minute",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(1439)],
                        verbose_name="Начало, минут от полуночи",
                    ),
                ),
                (
                    "end_minute",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(1440)],
                        verbose_name="Конец, минут от полуночи",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="market.shop",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "weekday", "method"), name="market_weekly_hours"
                    )
                ],
            },
        ),
    ]
