# Generated by Django 5.2.17 on 2026-10-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_at", models.DateTimeField()),
                (
                    "part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_payout",
                        to="market.shoporder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Демонстрационная выплата",
                "verbose_name_plural": "Демонстрационные выплаты",
                "ordering": ["-paid_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="market_demo_payout_nonnegative",
                    )
                ],
            },
        ),
    ]
