# Generated by Django 5.2.17 on 2026-10-06 11:41

from django.db import migrations, models

FLOWERS = (
    "Роза",
    "Роза кустовая",
    "Роза пионовидная",
    "Тюльпан",
    "Пион",
    "Хризантема",
    "Хризантема кустовая",
    "Гвоздика",
    "Гвоздика кустовая",
    "Эустома",
    "Гортензия",
    "Лилия",
    "Альстромерия",
    "Гербера",
    "Ранункулюс",
    "Ирис",
    "Орхидея",
    "Фрезия",
    "Гипсофила",
    "Ромашка",
    "Маттиола",
    "Дельфиниум",
    "Антуриум",
    "Калла",
    "Анемона",
    "Нарцисс",
    "Гиацинт",
    "Сирень",
    "Подсолнух",
    "Гладиолус",
    "Георгина",
    "Амариллис",
    "Протея",
    "Стрелиция",
    "Брассика",
    "Вероника",
    "Астильба",
    "Астранция",
    "Скабиоза",
    "Озотамнус",
    "Лимониум",
    "Солидаго",
    "Бувардия",
    "Ваксфлауэр",
    "Левкоспермум",
    "Нерине",
    "Агапантус",
    "Мускари",
    "Ландыш",
    "Гибискус",
)


def seed_flowers(apps, schema_editor):
    alias = schema_editor.connection.alias
    Flower = apps.get_model("market", "Flower")
    Listing = apps.get_model("market", "Listing")
    for rank, name in enumerate(FLOWERS):
        Flower.objects.using(alias).get_or_create(name=name, defaults={"rank": rank})
    # Keep exact known legacy values; never guess the contents of mixed bouquets.
    aliases = {
        "Розы": "Роза",
        "Пионы": "Пион",
        "Тюльпаны": "Тюльпан",
        "Хризантемы": "Хризантема",
        "Лилии": "Лилия",
        "Герберы": "Гербера",
    }
    for listing in Listing.objects.using(alias).exclude(flower_kind="").iterator():
        name = aliases.get(listing.flower_kind, listing.flower_kind)
        flower = Flower.objects.using(alias).filter(name=name).first()
        if flower:
            listing.flowers.add(flower)
    Listing.objects.using(alias).filter(category="stems").update(category="bouquet")


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_platform_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Цветок"),
                ),
                ("rank", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Цветок",
                "verbose_name_plural": "Цветы",
                "ordering": ["rank", "name"],
            },
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("bouquet", "Монобукеты"),
                    ("composition", "Композиции"),
                    ("basket", "Корзины"),
                    ("box", "В коробке"),
                ],
                default="bouquet",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="flowers",
            field=models.ManyToManyField(
                blank=True,
                related_name="listings",
                to="market.flower",
                verbose_name="Цветы в составе",
            ),
        ),
        migrations.RunPython(seed_flowers, migrations.RunPython.noop),
    ]
